ROCM_RPM=https://repo.radeon.com/amdgpu-install/22.20.3/sle/15.4/amdgpu-install-22.20.50203-1.noarch.rpm
ROCM_RELEASE=5.2.3
PYTORCH_VERSION=1.13.1+rocm5.2
PYTORCH_VERSION_SHORT=$(echo "$PYTORCH_VERSION" | cut -d '+' -f 1)
LIBTORCH_VERSION=1.13.1%2Brocm5.2
PYTHON_VERSION=3.10
WANDB_VERSION=0.16.3 
MKL_INCLUDE_VERSION=2024.0.0
NEQUIP_COMMIT=bffd533c60a05ff61b4cf9a5b0af8e8d940b66d5
ALLEGRO_COMMIT=22f673c565d148ae8e9394443baa9f5b5716c8e7
LAMMPS_VERSION=stable_2Aug2023_update2
PAIR_ALLEGRO_COMMIT=ae07ae51b990817f8f864065705f8bc5944c8f56
LAMMPS_VERSION=stable_2Aug2023_update2
